source 'https://rubygems.org'
ruby '2.4.1'

gem 'administrate'
gem 'asin'
gem 'autoprefixer-rails'
gem 'bourbon'
gem 'coffee-rails', '~> 4.2'
gem 'curb'
gem 'dragonfly'
gem 'dragonfly-s3_data_store'
gem 'jbuilder', '~> 2.5'
gem 'jquery-rails'
gem 'mini_racer'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.0'
gem 'rails-assets-trix', source: 'https://rails-assets.org'
gem 'rails', '~> 5.1.2'
gem 'redis', '~> 3.0'
gem 'sass-rails', '~> 5.0'
gem 'turbolinks', '~> 5'
gem 'uglifier', '>= 1.3.0'
gem 'vacuum'
gem 'vanilla-ujs'

group :production do
  gem 'skylight'
end

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'dotenv-rails'
end

group :development do
  gem 'listen', '~> 3.1.5'
  gem 'rails_real_favicon'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'spring'
  gem 'web-console'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
