regex:
  "hard on":
    - :sexual
  "jerk off":
    - :sexual
  "pissed off":
    - :inappropriate
  "damn it":
    - :inappropriate
  "the hell":
    - :inappropriate
simple:
  "god":
    - :inappropriate
  "jesus":
    - :inappropriate
  "christ":
    - :inappropriate
  "anus":
    - :sexual
  "arse":
    - :insult
  "arsehole":
    - :insult
  "ass":
    - :sexual :insult
  "ass-hat":
    - :insult
  "ass-pirate":
    - :discriminatory
  "assbag":
    - :insult
  "assbandit":
    - :discriminatory
  "assbanger":
    - :discriminatory
  "assbite":
    - :insult
  "assclown":
    - :sexual
  "asscock":
    - :insult
  "asscracker":
    - :sexual
  "asses":
    - :sexual
  "assface":
    - :sexual
  "ass-kick":
    - :sexual
  "ass-kicking":
    - :sexual
  "assfuck":
    - :sexual
  "assfucker":
    - :discriminatory
  "assgoblin":
    - :discriminatory
  "asshat":
    - :sexual
  "asshead":
    - :insult
  "asshole":
    - :insult
  "assholes":
    - :insult
  "asshopper":
    - :discriminatory
  "assjacker":
    - :discriminatory
  "asslick":
    - :insult
  "asslicker":
    - :insult
  "assmonkey":
    - :insult
  "assmunch":
    - :insult
  "assmuncher":
    - :sexual
  "assnigger":
    - :discriminatory
  "asspirate":
    - :discriminatory
  "assshit":
    - :insult
  "assshole":
    - :sexual
  "asssucker":
    - :insult
  "asswad":
    - :sexual
  "asswipe":
    - :sexual
  "bampot":
    - :insult
  "bastard":
    - :insult
  "beaner":
    - :discriminatory
  "beastial":
    - :sexual
  "beastiality":
    - :sexual
  "beastility":
    - :sexual
  "bestial":
    - :sexual
  "bestiality":
    - :sexual
  "bitch":
    - :insult
  "bitchass":
    - :insult
  "bitcher":
    - :insult
  "bitchers":
    - :insult
  #  "bitches":
    - :insult
  "bitchin":
    - :inappropriate
  "bitching":
    - :inappropriate
  "bitchtits":
    - :discriminatory
  "bitchy":
    - :insult
  "blow job":
    - :sexual
  "blowjob":
    - :sexual
  "blowjobs":
    - :sexual
  "bollocks":
    - :sexual
  "bollox":
    - :sexual
  "boner":
    - :sexual
  "brotherfucker":
    - :discriminatory
  "bullshit":
    - :inappropriate
  "bullshit":
    - :inappropriate
  "bumblefuck":
    - :discriminatory
  "butt plug":
    - :sexual
  "butt-pirate":
    - :discriminatory
  "buttfucka":
    - :discriminatory
  "buttfucker":
    - :discriminatory
  "camel toe":
    - :sexual
  "carpetmuncher":
    - :discriminatory
  "chinc":
    - :discriminatory
  "chink":
    - :discriminatory
  "choad":
    - :sexual
  "chode":
    - :sexual
  "clit":
    - :sexual
  "clitface":
    - :insult
  "clitfuck":
    - :sexual
  "clusterfuck":
    - :inappropriate
  "cock":
    - :sexual
  "cockass": "Jerk"
  "cockbite":
    - :insult
  "cockburger":
    - :insult
  "cockface":
    - :insult
  "cockfucker":
    - :insult
  "cockhead":
    - :insult
  "cockjockey":
    - :discriminatory
  "cockknoker":
    - :discriminatory
  "cockmaster":
    - :discriminatory
  "cockmongler":
    - :discriminatory
  "cockmongruel":
    - :discriminatory
  "cockmonkey":
    - :insult
  "cockmuncher":
    - :discriminatory
  "cocknose":
    - :insult
  "cocknugget":
    - :insult
  "cocks":
    - :sexual
  "cockshit":
    - :insult
  "cocksmith":
    - :discriminatory
  "cocksmoker":
    - :discriminatory
  "cocksuck":
    - :sexual
  "cocksucked":
    - :sexual
  "cocksucker":
    - :discriminatory :sexual
  "cocksucking":
    - :sexual :discriminatory
  "cocksucks":
    - :sexual :discriminatory
  "coochie":
    - :sexual
  "coochy":
    - :sexual
  "coon":
    - :discriminatory
  "cooter":
    - :sexual
  "cracker":
    - :discriminatory
  "cum":
    - :sexual
  "cum":
    - :sexual
  "cumbubble":
    - :insult
  "cumdumpster":
    - :sexual
  "cumguzzler":
    - :discriminatory
  "cumjockey":
    - :discriminatory
  "cummer":
    - :sexual
  "cumming":
    - :sexual
  "cums":
    - :sexual
  "cumshot":
    - :sexual
  "cumslut":
    - :sexual :insult
  "cumtart":
    - :insult
  "cunillingus":
    - :sexual
  "cunnie":
    - :sexual
  "cunnilingus":
    - :sexual
  "cunnilingus":
    - :sexual
  "cunt":
    - :insult :sexual
  "cuntface":
    - :insult
  "cunthole":
    - :sexual
  "cuntlick":
    - :sexual
  "cuntlicker":
    - :sexual :discriminatory
  "cuntlicking":
    - :sexual
  "cuntrag":
    - :insult
  "cunts":
    - :insult :sexual
  "cuntslut":
    - :insult
  "cyberfuc":
    - :sexual
  "cyberfuck":
    - :sexual
  "cyberfucked":
    - :sexual
  "cyberfucker":
    - :sexual
  "cyberfuckers":
    - :sexual
  "cyberfucking":
    - :sexual
  "dago":
    - :discriminatory
  "damn":
    - :inappropriate
  "deggo":
    - :discriminatory
  "dick":
    - :sexual :insult
  "dickbag":
    - :insult
  "dickbeaters":
    - :sexual
  "dickface":
    - :insult
  "dickfuck":
    - :insult
  "dickfucker":
    - :discriminatory
  "dickhead":
    - :insult
  "dickhole":
    - :sexual
  "dickjuice":
    - :sexual
  "dickmilk":
    - :sexual
  "dickmonger":
    - :discriminatory
  "dicks":
    - :sexual :insult
  "dickslap":
    - :sexual
  "dicksucker":
    - :discriminatory
  "dickwad":
    - :insult
  "dickweasel":
    - :insult
  "dickweed":
    - :insult
  "dickwod":
    - :insult
  "dike":
    - :discriminatory
  "dildo":
    - :sexual
  "dildos":
    - :sexual
  "dink":
    - :insult :sexual
  "dinks":
    - :sexual
  "dipshit":
    - :insult
  "doochbag":
    - :insult
  "dookie":
    - :inappropriate
  "douche":
    - :insult
  "douche-fag":
    - :insult
  "douchebag":
    - :insult
  "douchewaffle":
    - :discriminatory
  "dumass":
    - :insult
  "dumb ass":
    - :insult
  "dumbass":
    - :insult
  "dumbfuck":
    - :insult
  "dumbshit":
    - :insult
  "dumshit":
    - :insult
  "dyke":
    - :discriminatory
  "ejaculate":
    - :sexual
  "ejaculated":
    - :sexual
  "ejaculates":
    - :sexual
  "ejaculating":
    - :sexual
  "ejaculatings":
    - :sexual
  "ejaculation":
    - :sexual
  "fag":
    - :discriminatory
  "fagbag":
    - :discriminatory
  "fagfucker":
    - :discriminatory
  "fagging":
    - :discriminatory
  "faggit":
    - :discriminatory
  "faggot":
    - :discriminatory
  "faggot":
    - :discriminatory
  "faggotcock":
    - :discriminatory
  "faggs":
    - :discriminatory
  "fagot":
    - :discriminatory
  "fagots":
    - :discriminatory
  "fags":
    - :discriminatory
  "fagtard":
    - :discriminatory
  "fart":
    - :inappropriate
  "farted":
    - :inappropriate
  "farting":
    - :inappropriate
  "fartings":
    - :inappropriate
  "farts":
    - :inappropriate
  "farty":
    - :inappropriate
  "fatass":
    - :insult
  "felatio":
    - :sexual
  "fellatio":
    - :sexual
  "fellatio":
    - :sexual
  "feltch":
    - :sexual
  "fingerfuck":
    - :sexual
  "fingerfucked":
    - :sexual
  "fingerfucker":
    - :sexual
  "fingerfuckers":
    - :sexual
  "fingerfucking":
    - :sexual
  "fingerfucks":
    - :sexual
  "fistfuck":
    - :sexual
  "fistfucked":
    - :sexual
  "fistfucker":
    - :sexual
  "fistfuckers":
    - :sexual
  "fistfucking":
    - :sexual
  "fistfuckings":
    - :sexual
  "fistfucks":
    - :sexual
  "flamer":
    - :discriminatory
  "fuck":
    - :sexual
  "fuckass":
    - :insult
  "fuckbag":
    - :insult
  "fuckboy":
    - :insult
  "fuckbrain":
    - :insult
  "fuckbutt":
    - :sexual
  "fucked":
    - :sexual
  "fucker":
    - :sexual :insult
  "fuckers":
    - :sexual :insult
  "fuckersucker":
    - :insult
  "fuckface":
    - :insult
  "fuckhead":
    - :sexual
  "fuckhole":
    - :insult
  "fuckin":
    - :sexual
  "fucking":
    - :sexual
  "fuckings":
    - :sexual
  "fuckme":
    - :sexual
  "fucknut":
    - :insult
  "fucknutt":
    - :insult
  "fuckoff":
    - :insult
  "fucks":
    - :sexual
  "fucks":
    - :sexual
  "fuckstick":
    - :sexual
  "fucktard":
    - :insult
  "fuckup":
    - :insult
  "fuckwad":
    - :insult
  "fuckwit":
    - :insult
  "fuckwitt":
    - :insult
  "fudgepacker":
    - :discriminatory
  "fuk":
    - :sexual
  "fuks":
    - :sexual
  "gangbang":
    - :sexual
  "gangbanged":
    - :sexual
  "gangbangs":
    - :sexual
  "gay":
    - :discriminatory
  "gayass":
    - :sexual
  "gaybob":
    - :discriminatory
  "gaydo":
    - :discriminatory
  "gayfuck":
    - :discriminatory
  "gayfuckist":
    - :discriminatory
  "gaylord":
    - :discriminatory
  "gaysex":
    - :discriminatory
  "gaytard":
    - :discriminatory
  "gaywad":
    - :discriminatory
  "goddamn":
    - :inappropriate :blasphemy
  "goddamn":
    - :inappropriate :blasphemy
  "goddamnit":
    - :inappropriate :blasphemy
  "gooch":
    - :sexual
  "gook":
    - :discriminatory
  "gringo":
    - :discriminatory
  "guido":
    - :discriminatory
  "handjob":
    - :sexual
  "hardcoresex":
    - :sexual
  "heeb":
    - :discriminatory
  "hell":
    - :inappropriate
  "hell":
    - :inappropriate
  "ho":
    - :discriminatory
  "hoe":
    - :discriminatory
  "homo":
    - :discriminatory
  "homodumbshit":
    - :insult
  "honkey":
    - :discriminatory
  "horniest":
    - :sexual
  "horny":
    - :sexual
  "hotsex":
    - :sexual
  "humping":
    - :sexual
  "jackass":
    - :insult
  "jap":
    - :discriminatory
  "jigaboo":
    - :discriminatory
  "jism":
    - :sexual
  "jiz":
    - :sexual
  "jizm":
    - :sexual
  "jizz":
    - :sexual
  "jungle bunny":
    - :discriminatory
  "junglebunny":
    - :discriminatory
  "kike":
    - :discriminatory
  "kock":
    - :sexual
  "kondum":
    - :sexual
  "kondums":
    - :sexual
  "kooch":
    - :sexual
  "kootch":
    - :sexual
  "kum":
    - :sexual
  "kumer":
    - :sexual
  "kummer":
    - :sexual
  "kumming":
    - :sexual
  "kums":
    - :sexual
  "kunilingus":
    - :sexual
  "kunt":
    - :sexual
  "kyke":
    - :discriminatory
  "lesbian":
    - :discriminatory
  "lesbo":
    - :discriminatory
  "lezzie":
    - :discriminatory
  "lust":
    - :sexual
  "lusting":
    - :sexual
  "mcfagget":
    - :discriminatory
  "mick":
    - :discriminatory
  "minge":
    - :sexual
  "mothafuck":
    - :sexual
  "mothafucka":
    - :sexual
  "mothafucka":
    - :insult
  "mothafuckas":
    - :sexual
  "mothafuckaz":
    - :sexual
  "mothafucked":
    - :sexual
  "mothafucker":
    - :sexual :insult
  "mothafuckers":
    - :sexual :insult
  "mothafuckin":
    - :sexual
  "mothafucking":
    - :sexual
  "mothafuckings":
    - :sexual
  "mothafucks":
    - :sexual
  "motherfuck":
    - :sexual
  "motherfucked":
    - :sexual
  "motherfucker":
    - :sexual :insult
  "motherfuckers":
    - :sexual
  "motherfuckin":
    - :sexual
  "motherfucking":
    - :sexual
  "motherfuckings":
    - :sexual
  "motherfucks":
    - :sexual
  "muff":
    - :sexual
  "muffdiver":
    - :discriminatory :sexual
  "munging":
    - :sexual
  "negro":
    - :discriminatory
  "nigga":
    - :discriminatory
  "nigger":
    - :discriminatory
  "niggers":
    - :discriminatory
  "niglet":
    - :discriminatory
  "nut sack":
    - :sexual
  "nutsack":
    - :sexual
  "orgasim":
    - :sexual
  "orgasims":
    - :sexual
  "orgasm":
    - :sexual
  "orgasms":
    - :sexual
  "paki":
    - :discriminatory
  "panooch":
    - :sexual
  "pecker":
    - :sexual
  "peckerhead":
    - :insult
  "penis":
    - :sexual
  "penisfucker":
    - :discriminatory
  "penispuffer":
    - :discriminatory
  "phonesex":
    - :sexual
  "phuk":
    - :sexual
  "phuked":
    - :sexual
  "phuking":
    - :sexual
  "phukked":
    - :sexual
  "phukking":
    - :sexual
  "phuks":
    - :sexual
  "phuq":
    - :sexual
  "pis":
    - :sexual
  "pises":
    - :sexual
  "pisin":
    - :sexual
  "pising":
    - :sexual
  "pisof":
    - :sexual
  "piss":
    - :inappropriate
  "pissed":
    - :inappropriate
  "pisser":
    - :sexual
  "pissers":
    - :sexual
  "pisses":
    - :sexual
  "pissflaps":
    - :sexual
  "pissin":
    - :sexual
  "pissing":
    - :sexual
  "pissoff":
    - :sexual
  "polesmoker":
    - :discriminatory
  "pollock":
    - :discriminatory
  "poon":
    - :sexual
  "poonani":
    - :sexual
  "poonany":
    - :sexual
  "poontang":
    - :sexual
  "porch monkey":
    - :discriminatory
  "porchmonkey":
    - :discriminatory
  "porn":
    - :sexual
  "porno":
    - :sexual
  "pornography":
    - :sexual
  "pornos":
    - :sexual
  "prick":
    - :sexual
  "prick":
    - :sexual
  "pricks":
    - :sexual
  "punanny":
    - :sexual
  "punta":
    - :insult
  "pusies":
    - :sexual :insult
  "pussies":
    - :sexual :insult
  "pussy":
    - :sexual :insult
  "pussylicking":
    - :sexual
  "pussys":
    - :sexual
  "pusy":
    - :sexual
  "pusys":
    - :sexual
  "puto":
    - :insult
  "queef":
    - :sexual
  "queer":
    - :discriminatory
  "queerbait":
    - :discriminatory
  "queerhole":
    - :discriminatory
  "renob":
    - :sexual
  "rimjob":
    - :sexual
  "ruski":
    - :discriminatory
  "sandnigger":
    - :discriminatory
  "schlong":
    - :sexual
  "scrote":
    - :sexual
  "shit":
    - :sexual :inappropriate
  "shitass":
    - :insult
  "shitbag":
    - :insult
  "shitbagger":
    - :insult
  "shitbrains":
    - :insult
  "shitbreath":
    - :insult
  "shitcunt":
    - :insult
  "shitdick":
    - :insult
  "shited":
    - :sexual
  "shitface":
    - :insult
  "shitfaced":
    - :inappropriate :insult
  "shitfull":
    - :sexual
  "shithead":
    - :insult
  "shithole":
    - :insult
  "shithouse":
    - :inappropriate
  "shiting":
    - :sexual
  "shitings":
    - :sexual
  "shits":
    - :sexual
  "shitspitter":
    - :sexual
  "shitstain":
    - :inappropriate :insult
  "shitted":
    - :sexual
  "shitter":
    - :sexual
  "shitters":
    - :sexual
  "shittiest":
    - :inappropriate
  "shitting":
    - :inappropriate
  "shittings":
    - :sexual
  "shitty":
    - :inappropriate
  "shity":
    - :sexual
  "shiz":
    - :inappropriate
  "shiznit":
    - :inappropriate
  "skank":
    - :insult
  "skeet":
    - :sexual
  "skullfuck":
    - :sexual
  "slut":
    - :sexual
  "slut":
    - :discriminatory
  "slutbag":
    - :discriminatory
  "sluts":
    - :sexual
  "smeg":
    - :inappropriate
  "smut":
    - :sexual
  "snatch":
    - :sexual
  "spic":
    - :discriminatory
  "spick":
    - :discriminatory
  "splooge":
    - :sexual
  "spunk":
    - :sexual
  "tard":
    - :discriminatory
  "testicle":
    - :sexual
  "thundercunt":
    - :insult
  "tit":
    - :sexual
  "titfuck":
    - :sexual
  "tits":
    - :sexual
  "tittyfuck":
    - :sexual
  "twat":
    - :sexual
  "twatlips":
    - :insult
  "twats":
    - :sexual
  "twatwaffle":
    - :discriminatory
  "unclefucker":
    - :discriminatory
  "va-j-j":
    - :sexual
  "vag":
    - :sexual
  "vagina":
    - :sexual
  "vjayjay":
    - :sexual
  "wank":
    - :sexual
  "wetback":
    - :discriminatory
  "whore":
    - :insult
  "whorebag":
    - :insult
  "whoreface":
    - :insult
  "wop":
    - :discriminatory
