name: CI
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: ['12', '14']
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn type-check
        working-directory: packages/coquet
      - run: yarn build
        working-directory: packages/coquet
