sudo: false
language: node_js
cache:
  directories:
  - node_modules
git:
  depth: 1

node_js:
  - "5"
  - "4"
  - iojs

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script: make test-ci
