// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package mp4v2

import (
	"fmt"
	"math"
)

// MP4Integer32Array needs documentation
type MP4Integer32Array struct {
	mElements       []uint32
	mNumElements    MP4ArrayIndex
	mMaxNumElements MP4ArrayIndex
}

// ValidIndex needs documentation
func (a *MP4Integer32Array) ValidIndex(index MP4ArrayIndex) bool {
	return index < a.mNumElements
}

// Size needs documentation
func (a *MP4Integer32Array) Size() MP4ArrayIndex {
	return a.mNumElements
}

// MaxSize needs documentation
func (a *MP4Integer32Array) MaxSize() MP4ArrayIndex {
	return a.mMaxNumElements
}

// Add needs documentation
func (a *MP4Integer32Array) Add(newElement uint32) {
	a.Insert(newElement, a.mNumElements)
}

// Insert needs documentation
func (a *MP4Integer32Array) Insert(newElement uint32, newIndex MP4ArrayIndex) {
	if newIndex > a.mNumElements {
		panic("Illegal array index")
	}

	if a.mNumElements == a.mMaxNumElements {
		a.mMaxNumElements = MP4ArrayIndex(math.Max(float64(a.mMaxNumElements), 1) * 2)
		newMElements := make([]uint32, a.mMaxNumElements)
		copy(newMElements, a.mElements)
		a.mElements = newMElements
	}

	a.mElements[newIndex] = newElement
	a.mNumElements++
}

// Delete needs documentation
func (a *MP4Integer32Array) Delete(index MP4ArrayIndex) {
	if !a.ValidIndex(index) {
		panic(fmt.Sprintf("Illegal array index: %v of %v", index, a.mNumElements))
	}

	a.mNumElements--
	if index < a.mNumElements {
		a.mElements = append(a.mElements[:index], a.mElements[index+1:]...)
	}
}

// Resize needs documentation
func (a *MP4Integer32Array) Resize(newSize MP4ArrayIndex) {
	if newSize > a.mMaxNumElements {
		newMElements := make([]uint32, newSize)
		copy(newMElements, a.mElements)
		a.mElements = newMElements
	} else {
		a.mElements = a.mElements[:newSize]
	}

	a.mNumElements = newSize
	a.mMaxNumElements = newSize
}

// Get needs documentation
func (a *MP4Integer32Array) Get(index MP4ArrayIndex) uint32 {
	if a.ValidIndex(index) {
		return a.mElements[index]
	}

	panic(fmt.Sprintf("Illegal array index: %v of %v", index, a.mNumElements))
}

// Set needs documentation
func (a *MP4Integer32Array) Set(index MP4ArrayIndex, value uint32) {
	if a.ValidIndex(index) {
		a.mElements[index] = value
	}

	panic(fmt.Sprintf("Illegal array index: %v of %v", index, a.mNumElements))
}
