ruby '2.2.2'
source 'https://rubygems.org'

gem 'coffee-rails', '~> 4.1.0'
gem 'haml-rails', '~> 0.9'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'pg'
gem 'puma'
gem 'rails', '4.2.3'
gem 'sass-rails', '~> 5.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'therubyracer', platforms: :ruby
gem 'turbolinks'
gem 'typhoeus'
gem 'uglifier', '>= 1.3.0'

gem 'bootstrap-sass', '~> 3.3.5'
gem 'iso-639'
gem 'imdb', github: 'ariejan/imdb'
gem 'rottentomatoes'
gem 'canistreamit'
gem 'sidekiq'
gem 'sidekiq-unique-jobs'
gem 'sinatra', require: nil
gem 'vacuum'
gem 'sidekiq-throttler'
gem 'sidekiq-superworker'
gem 'sidekiq_monitor'
gem 'font-awesome-sass', '~> 4.3.0'
gem 'devise'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-twitter'
gem 'angularjs-rails'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  gem 'byebug'
  gem 'dotenv-rails'
  gem 'spring'
  gem 'web-console', '~> 2.0'
end
