FROM golang:1.10
LABEL maintainer="Jacob Gillespie <jacobwgillespie@gmail.com>"
MAINTAINER Jacob Gillespie <jacobwgillespie@gmail.com>

RUN apt-get update && apt-get -y install bash git make zip && apt-get clean && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*
RUN go get -u github.com/motemen/gobump/cmd/gobump
ADD . /go/src/github.com/jacobwgillespie/terraform-provider-script
WORKDIR /go/src/github.com/jacobwgillespie/terraform-provider-script
CMD ["make"]
