defaults: &defaults
  aws_key: secret
  aws_secret: secret
  s3_bucket: bucket_name
  zencoder_api_key: secret
  use_zencoder: true
  stripe_api_key: secret
  airbrake_api_key: secret
  elasticsearch_server: 127.0.0.1:9200
  newrelic_rpm:
    app_name: <%= ENV["NEW_RELIC_APP_NAME"] %>
    license_key: <%= ENV["NEW_RELIC_LICENSE_KEY"] %>
  allowed_upload_types:
    documents: [pdf, doc, docx, rtf, md]
    photos: [png, jpg, jpeg, tiff]
    audio: [mp3, wav, wma]
    video: [mov, avi, mp4, mkv, wmv, mpg]

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
